language: generic 
sudo: required
services:
 - docker
before_install:
 - docker build -t learn_docker -f dockerfile.dev .
script:
 - docker run -e CI=true learn_docker npm run test -- --coverage
deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker"
 env: "docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-059476099389"
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY